# Configure main menu and social menu
main:
  - identifier: tag
    name: TAG
    url: https://tagss04.pro/#/auth/2neqgxFl
    params:
      icon: flame
      newtab: true

social:
  - identifier: github
    name: GitHub
    url: https://github.com/jf666666
    params:
      icon: brand-github
  - identifier: telegram
    name: Telegram
    url: https://t.me/jf666666
    params:
      icon: brand-telegram
  # - identifier: twitter
  #   name: Twitter
  #   url: https://twitter.com
  #   params:
  #     icon: brand-twitter
